### ISSUE TITLE
SublimeText graphs messed up

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaPlots/UnicodePlots.jl#100]
First of all, many thanks for this useful package! I love that it is so lightweight, and yet powerful.

I am having some issues with plotting in the Sublime Text terminal. Any idea what is going on and how to fix it?
![image](https://user-images.githubusercontent.com/9855832/56865622-1aa37e80-6985-11e9-8e2b-653ccf6314e9.png)

**Comment by PetrKryslUCSD** [comment]
I don't know yet why it looks like that, but at least now I chanced upon a way of fixing the display. Selecting the DotCanvas seems to do the trick.
```
plt = lineplot(geom.values[nLx,1][ix], real(P.values)[nLx][ix], canvas = DotCanvas, title = "Steady-state pressure", name = "real", xlabel = "x", ylabel = "P")
plt = lineplot!(plt, geom.values[nLx,1][ix], imag(P.values)[nLx][ix], name = "imag")
display(plt)
```

**Comment by Evizero** [comment]
Yes this is a known issue with the Braille Characters in almost any setting aside a terminal. `DotCanvas` is the only known workaround thus far

**Comment by Evizero** [comment]
see https://github.com/Evizero/UnicodePlots.jl/issues/9#issuecomment-455814080 for related discussion

**Comment by PetrKryslUCSD** [comment]
Got it. Thanks!

**Comment by t-bltg** [comment]
Closing in favor of https://github.com/JuliaPlots/UnicodePlots.jl/issues/9.
