### ISSUE TITLE
heatmap not working

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaPlots/UnicodePlots.jl#104]
All examples in readme work, aside from heatmap:
```julia 
julia> using UnicodePlots
julia> heatmap(repeat(collect(0:10)', outer=(11, 1)), zlabel="z")
ERROR: UndefVarError: heatmap not defined
Stacktrace:
 [1] top-level scope at REPL[24]:1
```

**Comment by Evizero** [comment]
currently only on `master`

**Comment by mmattocks** [comment]
Are there any hints as to why this might be happening? I would like to help if possible.

**Comment by Evizero** [comment]
The latest commits are not yet tagged. The project isn't upgraded to the current Pkg version #103

**Comment by mmattocks** [comment]
Ah, of course! Thank you!

**Comment by Datseris** [comment]
Hi @Evizero , if I do a PR that updates this to `Pkg`, and thus Julia 1.0, would you accept it? It has to remove REQUIRE as a consequence.

**Comment by goretkin** [comment]
Looks like a new version can be tagged now! Is that right?

**Comment by Evizero** [comment]
https://github.com/Evizero/UnicodePlots.jl/commit/625ba36b2dc402839a1401a6e90a650c7668eb06

If someone makes a tagbot file PR for the new system, I'd happily merge it
