### ISSUE TITLE
Plots don't look good on windows powershell

### ISSUE THREAD

**Issue by freddy-turtle** [JuliaPlots/UnicodePlots.jl#110]
![capture_20191223162230933](https://user-images.githubusercontent.com/4253344/71365931-bf23a200-25a0-11ea-9cd2-213fe7d3291f.png)

**Comment by fredlnl** [comment]
works on git bash

**Comment by equinaut** [comment]
Git bash working isn’t surprising, I think that’s basically a terminal emulator. I believe adjusting the canvas type helps with this:

`lineplot(sin, 1:.5:20, labels=false, canvas=AsciiCanvas)`

I’d imagine DotCanvas would also look good. 

I don’t recall why this is an issue with windows, or if there’s any possibility of a better default given OS.

**Comment by equinaut** [comment]
Actually there's a related issue [here](https://github.com/Evizero/UnicodePlots.jl/issues/98#issuecomment-455868916), with what appears to be a game plan to set the default canvas given the platform.

**Comment by Moelf** [comment]
https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701

time to move to modern tool (not that I use Windows or know it would work but I assume it does because it has better fonts etc.)
