### ISSUE TITLE
Request: Increase resolution of bar graphics

### ISSUE THREAD

**Issue by jakobnissen** [JuliaPlots/UnicodePlots.jl#124]
Currently, histogram uses `▇` (U+2587). Full blocks are not used presumably because the small space up to the next block makes it easier to distinguish between the lines along their lengths.

However, the reader don't actually need to distinguish between the lines along their lengths - consider that the information in a histogram could also be conveyed by a line plot. The only reason histograms even use bars is to convey the "blocked look" that represents binned data.

If, instead, the character range `█:▏` (U+2588 : U+258F) is used, we increase the resolution 8-fold.
E.g. a histogram that looked like this before
```
▇▇▇▇▇▇▇▇▇▇ 100
▇▇▇▇▇▇▇▇▇▇ 98 (indistinguishable from 100)
▇ 13
 3 (appears like 0)
▇▇▇▇ 36 (rounding error of almost 15% in bar length)
```
Would now appear like:
```
██████████ 100
█████████▊ 98
█▍13
▎3
███▋36
```
And therefore represent the data more accurately. Here's how they look like in my terminal
<img width="156" alt="image" src="https://user-images.githubusercontent.com/23193950/94527608-87384200-0237-11eb-9cfe-8d712c09fd79.png">

**Comment by Evizero** [comment]
I did consider going this route but took the easy path. The barplot was already implemented so by using a single block character all that was left to do was computing the data and plot it using the barplot logic. The little separation space between the blocks was just a bonus that came for free and was a completely subjective choice based on me liking the look of it.

I am open to this change
