### ISSUE TITLE
histogram bug type Int64 has no field hi

### ISSUE THREAD

**Issue by Moelf** [JuliaPlots/UnicodePlots.jl#130]
```julia
using StatsBase

julia> histogram(fit(Histogram, rand(100).*10, 0:1:2))
ERROR: type Int64 has no field hi
```

This happens because in `StepRange{Int64, Int64}`, there's no `step.hi`. Should be a good first-time PR kinda issue.

Needs extra check here: https://github.com/Evizero/UnicodePlots.jl/blob/3ba7e6326d38453db6a9a7b43f03c082f10d9fe1/src/interface/histogram.jl#L93

**Comment by aminnj** [comment]
did this get fixed somewhere else? `master` gives me

```julia
julia> using UnicodePlots, StatsBase

julia> histogram(fit(Histogram, rand(100).*10, 0:1:2))
              ┌                                        ┐
   [0.0, 1.0) ┤████████████████████████████████████▏ 14
   [1.0, 2.0) ┤███████████████████████▎ 9
              └                                        ┘
                              Frequency
```

**Comment by t-bltg** [comment]
Maybe https://github.com/JuliaPlots/UnicodePlots.jl/pull/149 ?

**Comment by johnnychen94** [comment]
Looks like this is already covered by the tests in #149 so I'm going to close it.

**Comment by t-bltg** [comment]
I love those side effect closing more issues than they originally should :laughing:
