### ISSUE TITLE
adapt the height / width to displaysize of the terminal

### ISSUE THREAD

**Issue by ghost** [JuliaPlots/UnicodePlots.jl#131]
`displaysize(io)` can be used to make graph fit the size of the terminal without special tweaking of the inputs, for example:

```julia
function lplot(a...; kw...)
    height, width = displaysize(stdout) .- 10
    height = min(height, width ÷ 3)
    lineplot(a...; height=height, width=width, kw...)
end
```

Worth considering?

**Comment by t-bltg** [comment]
Linked: https://github.com/JuliaPlots/UnicodePlots.jl/issues/115
