### ISSUE TITLE
`histogram!` please!

### ISSUE THREAD

**Issue by bjarthur** [JuliaPlots/UnicodePlots.jl#132]
the README says "Every plot has a mutating variant that ends with a exclamation mark." but this is not the case for `histogram`.  :(  would be a useful feature to have.

**Comment by t-bltg** [comment]
I'm not sure this is feasible.

**Comment by waldyrious** [comment]
> EDIT: update the docs, to change the assertion.

Note, for future reference: that change was done in https://github.com/JuliaPlots/UnicodePlots.jl/pull/163/files.
