### ISSUE TITLE
UnicodePlots.jl is failing on the daily PkgEval runs

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaPlots/UnicodePlots.jl#134]
UnicodePlots.jl is failing on the daily PkgEval runs. See for example: https://juliaci.github.io/NanosoldierReports/pkgeval_badges/U/UnicodePlots.html

[pkgeval-img]: https://juliaci.github.io/NanosoldierReports/pkgeval_badges/U/UnicodePlots.named.svg
[pkgeval-url]: https://juliaci.github.io/NanosoldierReports/pkgeval_badges/U/UnicodePlots.html

[![PkgEval][pkgeval-img]][pkgeval-url]

**Comment by Evizero** [comment]
looks like the cause is here

```
ERROR: LoadError: ArgumentError: Package Random not found in current path:
- Run `import Pkg; Pkg.add("Random")` to install the Random package.
```

**Comment by waldyrious** [comment]
@johnnychen94 shouldn't this issue be reopened, considering that the PkgEval runs are still failing?

**Comment by johnnychen94** [comment]
Intersting... I thought #136 fixes this already.

**Comment by t-bltg** [comment]
Seems like we lost some `ansi` color codes with `1.8.0`.

**Comment by t-bltg** [comment]
Test pass on `1.7.0 rc1`.
Test pass on nightly `1.8.0` (`Version 1.8.0-DEV.593 (2021-09-24) - Commit 53aa65ad3c (1 day old master)`).

@DilumAluthge, this looks like a `CI` specific issue, not sure how I can fix this without more info.

**Comment by DilumAluthge** [comment]
Here's the log: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2021-09/25/UnicodePlots.1.8.0-DEV-53aa65ad3c9.log

I think it has to do with color. Color is disabled in PkgEval.

cc: @maleadt

**Comment by johnnychen94** [comment]
Do we have a way to detect if color is enabled inside Julia? If so we can optionally disable some color tests.

**Comment by maleadt** [comment]
```
julia> Base.get_have_color()
true
```

Not sure how officially sanctioned that is though.

**Comment by DilumAluthge** [comment]
> ```
> julia> Base.get_have_color()
> true
> ```
> 
> 
>      
>   
> 
> Not sure how officially sanctioned that is though.

On older Julia versions, I don't think that will work. This is what @KristofferC does in Crayons.jl to support both older and newer Julia versions:

```Julia
function _have_color()
    if isdefined(Base, :get_have_color)
        return Base.get_have_color()
    else
        Base.have_color
    end
end
```

Source: https://github.com/KristofferC/Crayons.jl/blob/2619561156a02fdf739c8146e09a96ceb176f43c/src/crayon.jl#L102

**Comment by KristofferC** [comment]
>  This is what @KristofferC does in Crayons.jl to support both older and newer Julia versions:

I am not sure this is a good way at all though.

I think the correct way is to always print to an `IO` with color enabled:

```
base ❯ julia -q --color=no

julia> printstyled(IOContext(stdout, :color => true), "foo"; color=:green)
foo # printed in green anyway
```

**Comment by DilumAluthge** [comment]
> > This is what @KristofferC does in Crayons.jl to support both older and newer Julia versions:
> 
> I am not sure this is a good way at all though.
> 
> I think the correct way is to always print to an `IO` with color enabled:
> 
> ```
> base ❯ julia -q --color=no
> 
> julia> printstyled(IOContext(stdout, :color => true), "foo"; color=:green)
> foo # printed in green anyway
> ```

If I recall, we tried that approach, but it still ended up failing on PkgEval.

**Comment by KristofferC** [comment]
It is maybe Crayons.jl fault then. https://github.com/KristofferC/Crayons.jl/issues/47 maybe.

**Comment by DilumAluthge** [comment]
Ahhhh yeah it might be https://github.com/KristofferC/Crayons.jl/issues/47.

**Comment by t-bltg** [comment]
Thanks for the hints. We don't use `show`, we use `Crayon.val(...)` (see https://github.com/JuliaPlots/UnicodePlots.jl/blob/f7c123edc81ead3a579ba2299e0ed7b8c71ea4ef/src/common.jl#L260).

I'm gonna test with `julia --color=no` and see if I can reproduce this locally.

**Comment by t-bltg** [comment]
Confirmed fix, `UnicodePlots` is absent from today's [nanosoldier report](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_date/2021-09/27/report.md).

**Comment by waldyrious** [comment]
> Confirmed fix, UnicodePlots is absent from today's nanosoldier report.

Nice! Btw, perhaps the PkgEval badge (as shown in the [opening commit](https://github.com/JuliaPlots/UnicodePlots.jl/issues/134#issue-857152475)) could be added to the README, next to the other CI ones?
