### ISSUE TITLE
Consider making `UnicodePlots` part of the `JuliaPlots` organization

### ISSUE THREAD

**Issue by t-bltg** [JuliaPlots/UnicodePlots.jl#146]
As discussed in https://github.com/Evizero/UnicodePlots.jl/pull/136#issuecomment-900160398, transferring [`UnicodePlots`](https://github.com/Evizero/UnicodePlots.jl) to the [`JuliaPlots`](https://github.com/JuliaPlots) organization would ease maintenance and integration in [`Plots.jl`](https://github.com/JuliaPlots/Plots.jl).

@Evizero, what's your opinion on this ?

**Comment by BeastyBlacksmith** [comment]
I think that was already discussed in https://github.com/Evizero/UnicodePlots.jl/issues/123

**Comment by johnnychen94** [comment]
FWIW, I'll be around watching this repo, merge anything that works and improves the status in a non-controversial way. But being distracted by too many repos, I probably won't be able to really contribute codes here.

It would be convenient if there are people from JuliaPlots being granted with write or maintainer permission.

**Comment by Evizero** [comment]
While I m quite attached to UnicodePlots for some sentimental reason, I do need to recognize that this package has outlived my Julia days. As things stand i doubt I'll make a comeback in the next 1-2 years given my current responsibilities. While I am a little sentimental, I am also quite proud that I was able to contribute a little bit of code that the community is still actively using to this day.

So in the spirit of open source, I would be happy and honored to transfer UnicodePlots to JuliaPlots if:
- Someone else takes care of all things necessary to ensure a smooth transition after I transfered the package.
- Some active JuliaPlots member takes over the responsibility of maintenance for the near future.

**Comment by Evizero** [comment]
Since I am a bit out of the loop could someone ping JuliaPlots members that this issue might be of interest to?

**Comment by BeastyBlacksmith** [comment]
@daschw @mkborregaard @SimonDanisch

**Comment by mkborregaard** [comment]
Maybe transfer to JuliaPlots and make @johnnychen94 a collaborator with write access on that repo? This package has 98% unit test coverage so passive maintenance in JuliaPlots should not be a big task.

**Comment by t-bltg** [comment]
> While I m quite attached to UnicodePlots for some sentimental reason, I do need to recognize that this package has outlived my Julia days. As things stand i doubt I'll make a comeback in the next 1-2 years given my current responsibilities. While I am a little sentimental, I am also quite proud that I was able to contribute a little bit of code that the community is still actively using to this day.
> 
> So in the spirit of open source, I would be happy and honored to transfer UnicodePlots to JuliaPlots if:
> 
>     * Someone else takes care of all things necessary to ensure a smooth transition after I transfered the package.
> 
>     * Some active JuliaPlots member takes over the responsibility of maintenance for the near future.

Thanks for you detailed answer !
I believe that the active members of the `JuliaPlots` organization will be able to maintain `UnicodePlots` in a proactive way towards constantly improving pieces of opensource software.

> Maybe transfer to JuliaPlots and make @johnnychen94 a collaborator with write access on that repo? This package has 98% unit test coverage so passive maintenance in JuliaPlots should not be a big task.

Well this is the spirit: transferring to the organization will grant members of that organization write access, so that things can run smoothly (in a peer reviewed mechanism way).

**Comment by t-bltg** [comment]
> Someone else takes care of all things necessary to ensure a smooth transition after I transfered the package.
> Some active JuliaPlots member takes over the responsibility of maintenance for the near future.

No one showed up, so I'm volunteering for that.

**Comment by johnnychen94** [comment]
I think we first need to invite @Evizero to be a member of JuliaPlots first to start the transition?

**Comment by BeastyBlacksmith** [comment]
He is already a member of JuliaPlots

**Comment by Evizero** [comment]
It is done. I am unsure about permission for @t-bltg . I recon I should have set them before moving the package. Someone please give him access.

Thank you all

**Comment by mkborregaard** [comment]
@t-bltg is a member with full push privs.
Great!

**Comment by t-bltg** [comment]
This is great, thanks @Evizero !
