### ISSUE TITLE
[FR] Support sixel encoding

### ISSUE THREAD

**Issue by johnnychen94** [JuliaPlots/UnicodePlots.jl#153]
It would be super cool if we can bring sixel support for terminal plots, I've made a libsixel wrapper https://github.com/johnnychen94/Sixel.jl Check https://github.com/csdvrx/sixel-gnuplot for the sixel gallery.

There are two possible solutions:

* easy but slow one: for any plot library that can output an image or `Array{<:Colorant}`, pass the colorant array to `Sixel.sixel_encode` and thus get a nice terminal view
* difficult but (maybe) efficient one: https://en.wikipedia.org/wiki/ReGIS I'm not sure if Sixel.jl is ready for ReGIS format.

**Comment by johnnychen94** [comment]
Looks like GR also have built-in sixel support https://discourse.julialang.org/t/plots-in-the-terminal-with-sixel/22503/4

![image](https://user-images.githubusercontent.com/8684355/131879525-020b2169-f825-465f-87e5-95cc8adecb35.png)

**Comment by johnnychen94** [comment]
@t-bltg Will it be too tricky for Plots to add a virtual backend for Sixel by 1) loading the PNG output of another backend, 2) encode to sixel using Sixel.jl, and 3) print to terminal? Maybe we can pirate the `UnicodePlotsBackend` when sixel is supported by the terminal?

https://github.com/JuliaImages/ImageInTerminal.jl/pull/50 is what I did for ImageInTerminal to auto-switch to sixel encoding.

**Comment by t-bltg** [comment]
I'll give it a try in the next few days !

**Comment by waldyrious** [comment]
Just a side note that supporting sixel would probably make this package more like a TerminalPlots.jl than a UnicodePlots.jl :)

**Comment by t-bltg** [comment]
@johnnychen94 I think we can work on this now.

I don't think I fully understand the sixel format, could you point to we a simple implementation (what's the base type to encode a sixel ?).

**Comment by johnnychen94** [comment]
You can think of sixel as an advanced ANSI sequence for image types.

```julia
using Sixel
img = testimage("mandril")
sixel_encode(img)
```

**Comment by t-bltg** [comment]
How can I determine how many sixel there are for this image of `512×512` RGB values ?.

**Comment by johnnychen94** [comment]
The technical format says that one control code consists of 6 pixels, which is why the term "sixel" comes from ("six pixels"). Given that Sixel.jl is currently only a wrapper package for libsixel, there isn't a way to do pixel-level encoding.

I was thinking of something like

```julia
plt = plot(sin.(1:10))
png(plt, "tmp.png")
img = load("tmp.png")
print(sixel_encode(img))
```

![image](https://user-images.githubusercontent.com/8684355/132361473-4b68feae-f618-45cb-ab9e-88d06f2d0855.png)


but don't know how to skip the filesystem IO ("tmp.png"). I believe it's doable with `IOBuffer()` but needs to try some.

**Comment by johnnychen94** [comment]
Ohohoh yes!

![image](https://user-images.githubusercontent.com/8684355/132362765-ecc9d08b-3500-4fd4-94b4-02680c58dc2d.png)

**Comment by johnnychen94** [comment]
> Still do you think UnicodePlots needs somehing like imageplot to just display images ?

Do you mean `ImageInTerminal`?

**Comment by t-bltg** [comment]
> Do you mean ImageInTerminal.jl, which was also created by @evizero :)

No I mean here in `UnicodePlots`, so that we can embed and image in a plots as in http://docs.juliaplots.org/latest/generated/gr/#gr-ref6.

Maybe we can detect `ImageInTerminal` and use it in `UnicodePlots` for displaying raw images (see https://github.com/JuliaPlots/UnicodePlots.jl/pull/88#issuecomment-511288133). We then of course delegate to `imshow`.

> This semester just starts so I'm not available recently, will do it when I find some time.
Ok

**Comment by johnnychen94** [comment]
> Maybe we can detect ImageInTerminal and use it in UnicodePlots for displaying raw images (see #88 (comment)). We then of course delegate to imshow.

If we need to draw borders then I don't think we can directly use codes from ImageInTerminal unless we duplicate the codes; in UnicodePlots we then need to redraw at the pixel level and ImageInTerminal API is for image level.

I haven't thought this very carefully, but my guess is: if we want to combine both plots and image display, we need to provide a terminal display abstraction and protocol (a Julia-version tmux stuff).
