### ISSUE TITLE
[FR] stand-alone version of `printcolorbarrow` to draw a colorbar in isolation

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaPlots/UnicodePlots.jl#169]
this is a feature request to draw a colorbar in isolation with a specific range, via something like
```julia
draw_colorbar(colormap = [(x.r, x.g, x.b) for x in ColorSchemes.leonardo.colors], title="concentration", range=(0.0, 10.0))
```
to give

![image](https://user-images.githubusercontent.com/30643894/132265694-466df1db-df65-4855-bc0f-02cf436696fd.png)

instead of using this:
```julia
using UnicodePlots, ColorSchemes
heatmap(10*rand(50, 50); title = "Hot!",
           colormap = [(x.r, x.g, x.b) for x in ColorSchemes.leonardo.colors])
```
(basically, I want to remove the un-needed heatmap from this portion of the code).

thx, awesome package!

PS I need this to go along with `GraphPlot` to show the colormap that colors nodes in a graph.

**Comment by t-bltg** [comment]
@SimonEnsemble, sorry for the delay, this was not on top of my priority list.

Using https://github.com/JuliaPlots/UnicodePlots.jl/pull/199, is the syntax for plotting an isolated colorbar `Plot([0], [0], colorbar=true, colormap=:cividis, width=0, min_width=0)` ok for you ?

**Comment by SimonEnsemble** [comment]
it works, thank you!

<img width="151" alt="image" src="https://user-images.githubusercontent.com/30643894/149817138-e5c07aa4-d15f-4dc2-a8e8-d3027a7c15bb.png">

though would be nice to somehow make `plot([], [], ...)` work to remove the bounding box/plot so that it is *just* a colorbar.

**Comment by t-bltg** [comment]
Yes, this would be done it a following PR (which I'm writing now, since https://github.com/JuliaPlots/UnicodePlots.jl/pull/199 has been split in multiple PRs.

**Comment by t-bltg** [comment]
PR is now open at https://github.com/JuliaPlots/UnicodePlots.jl/pull/205.

![isolated](https://user-images.githubusercontent.com/13423344/149818250-bfd47c33-b68d-4e26-845f-4e27ff426a8f.png)

**Comment by SimonEnsemble** [comment]
😍 nice! it works for me!
is there an option to change the colorbar limits too? this is stuck at 0-1.
this will be useful for when coloring e.g. nodes of graphs according to some scheme.

**Comment by t-bltg** [comment]
Yes, `colorbar_lim = (0, 100)`, it should be documented, so I've added a description for that in https://github.com/JuliaPlots/UnicodePlots.jl/pull/205.

It should then appeat in
```julia
help?> Plot
```
