### ISSUE TITLE
[FR] Text annotations

### ISSUE THREAD

**Issue by mtfishman** [JuliaPlots/UnicodePlots.jl#170]
Thanks for the great package! I love the idea of making quick plots and visualizations right in the REPL.

I was wondering if there was a way to make text annotations _within_ the plot (I see a lot of options for adding annotations around the boundary of the plot with the `annotate!` function). I think the answer is no right now, but I wanted to double check.

My use case is that I would like to make a lightweight REPL backend alternative for doing tensor network visualizations with my package [ITensorsVisualization.jl](https://github.com/ITensor/ITensorsVisualization.jl), which currently uses Makie as a backend so that the visualizations can be interactive. The graphs can be pretty complicated, in general tensor networks can be directed and weighted multigraphs with quite a bit of metadata (MetaMultiWeightedDiGraph?), but for the sake of simplicity for use with UnicodePlots it could be visualized as a simple undirected graph. However, in order to understand the graph that gets plotted, it would be very helpful to have text annotations to label the nodes and edges of the graph.

Here is a minimal example I cooked up making a network visualization using `GraphRecipes` with `UnicodePlots` as a backend:
```julia
using LightGraphs, GraphRecipes, Plots

n = 5
g = wheel_graph(n)

edgelabel_dict = Dict()
for i in 1:n, j in 1:n
  edgelabel_dict[(i, j)] = string("edge ", i, " to ", j)
end

gr()
plt_gr = graphplot(g, edgelabel=edgelabel_dict, names=vertices(g), markershape=:circle, curves=false)
savefig(plt_gr, "wheelgraph")

unicodeplots()
plt_up = graphplot(g, edgelabel=edgelabel_dict, names=vertices(g), markershape=:circle, curves=false)
```
outputs:
```julia
julia> plt_up
        ┌────────────────────────────────────────┐ 
    0.7 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ 
        │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⡀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ 
        │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡠⠛⡟⢼⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ 
        │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠔⠁⠀⢇⢸⠀⠉⠢⢄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ 
        │⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⢀⠔⠑⢀⠀⠀⢸⢸⠀⢈⠐⠀⠈⠑⠢⣀⠀⠀⡁⠀⠀⠀⠀⠀⠀⠀⠀⠀│ 
        │⠀⠀⠀⠀⠀⠀⠀⠠⠀⠀⢀⠔⠁⠀⠈⠠⠀⠀⠀⣿⠀⠀⠈⠀⠀⠀⠀⠀⠉⠒⠤⣀⠀⠀⠀⠀⠀⠀⠀⠀│ 
        │⠀⠀⠀⠀⠀⠀⠀⠀⢀⠔⠁⠀⠀⠀⠀⠀⠀⠀⠀⢹⠀⠀⠀⠄⠀⠀⠀⠀⢀⣀⣀⣄⣑⢶⣶⠄⠀⠀⠀⠀│ 
        │⠤⠤⠤⠤⠤⠤⢤⠴⠥⠤⠤⣤⣤⣤⣤⡤⠤⠤⠤⢾⡷⠶⠶⠶⠭⠭⠭⠭⠥⠤⠤⢦⠴⠥⠤⠤⠤⠤⠤⠄│ 
        │⠀⠀⠀⠀⠐⠿⠯⢍⡙⠉⠉⠀⠀⠀⠀⠀⠐⠀⠀⢸⢣⠀⠀⠀⠀⠀⠀⠀⠀⢀⠔⠁⠀⠀⠀⠀⠀⠀⠀⠀│ 
        │⠀⠀⠀⠀⠀⠀⠀⠀⠈⠒⠤⣀⠀⠀⠀⠀⠀⡀⠀⢸⠸⡀⠀⠀⠂⡀⠀⢀⠔⠁⠀⠀⠂⠀⠀⠀⠀⠀⠀⠀│ 
        │⠀⠀⠀⠀⠀⠀⠀⠀⠀⢈⠀⠀⠉⠢⢄⡀⠀⠄⡁⢸⠀⡇⠀⠀⠁⢄⠔⠁⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀│ 
        │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠑⠢⣀⢸⠀⢸⠀⢀⠔⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ 
        │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⠒⣬⣦⠊⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ 
        │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠈⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ 
   -0.7 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ 
        └────────────────────────────────────────┘ 
        ⠀-0.7⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀0.7⠀ 
```
The formatting is a bit off when pasting into Github, but I think you get the idea. Note that the labels don't show up on the nodes or edges. It appears to try to put some basic version of a box where the edge labels are supposed to go. Here is the output with a GR backend:

![wheelgraph](https://user-images.githubusercontent.com/7855256/132537820-bdd34988-931a-4ebb-8f42-1a6c7a45fab7.png)

I would be happy to help with adding this feature, but would need some pointers on how to get started. I tried starting by looking at how the `UnicodePlots.annotate!` function works but I couldn't tell how to generalize it to putting annotations at a custom location.

Some of this would no doubt need some coordination with the `GraphRecipes.jl` package and maybe even `Plots.jl`. For example, it would be nice if the `GraphRecipes` plot didn't show the border, labels, and grid by default for graph visualizations, but the `UnicodePlots` keyword arguments `(border=:none, labels=false, grid=false)` don't get passed along properly to `UnicodePlots` when I use `GraphRecipes.graphplots`. Those work fine if I circumvent `GraphRecipes` and make a custom graph visualization directly with `UnicodePlots.lineplot!`.

**Comment by t-bltg** [comment]
Great idea for improvement ! Supporting arbitrary annotations would be useful for `Plots.jl`.

The `annotate!` in `plot.jl` function operates outside the canvas for setting labels, so we need instead to operate at canvas level.
For each canvas, `printrow` outputs the colorized `grid` content to an output stream.

At least for a `BrailleCanvas` it should be easy to write a `text`, annotate`, or `note` function replacing arbitrary characters in the `grid` which is an `Array{Char}` (see [here](https://github.com/JuliaPlots/UnicodePlots.jl/blob/f740f2ba981f17a4e83c1f7ceb5775ccce07989c/src/canvas/braillecanvas.jl#L13)).

For other canvases, e.g. `AsciiCanvas` (UInt16), `DotCanvas` (UInt8) or `BlockCanvas` (UInt8) which are specializations of `LookupCanvas` it should be feasible with a bit of extra work (write a simple encoder/decoder which must fit the underlying type).
