### ISSUE TITLE
Layouts don't work from the REPL?

### ISSUE THREAD

**Issue by GlenHenshaw** [JuliaPlots/UnicodePlots.jl#197]
In the examples, the following:

    > using Plots
    > using UnicodePlots
    > unicodeplots()
    > plot(Plots.fakedata(100, 10), layout=4)

sure seems like it should result in a 2x2 grid of plots.

But it doesn't. At least not for me (Julia 1.7.1, UnicodePlots 2.5.1). It results in four plots arranged vertically. No other value for layout results in anything different -- all the plots are placed in a single width column, no matter what.

**Comment by t-bltg** [comment]
This is expected, there have been some changes in `Plots.jl` merged in master but not yet released (https://github.com/JuliaPlots/Plots.jl/pull/4021).

For now you can use `show(plot(Plots.fakedata(100, 10), layout=4))`.

In the following release, you will use either `display(plot(Plots.fakedata(100, 10), layout=4))` or just `plot(Plots.fakedata(100, 10), layout=4)`.

**Comment by t-bltg** [comment]
I've just released a new version of Plots (https://github.com/JuliaPlots/Plots.jl/commit/47ca50d03789377093ae1805cd9886609fa4a574). It should be available from registry within about 15/30 min.

After upgrading to `Plots@1.25.5` you should see a `2x2` grid with your example.
