### ISSUE TITLE
Vertical Unicode Histogram feature 

### ISSUE THREAD

**Issue by Cvikli** [JuliaPlots/UnicodePlots.jl#219]
Dear Julianners of UnicodePlots,

I just wanted to ask weather you want to merge this few lines of code of mine to your repository:
[https://github.com/Cvikli/HistogramUnicode.jl](https://github.com/Cvikli/HistogramUnicode.jl)
We were having discussion about this topic here: [Julia Discourse - BenchmarkTools @benchmark beautiful histogram reuse](https://discourse.julialang.org/t/benchmarktools-benchmark-beautiful-histogram-reuse/75053/4)

I don't know your standards, for me this function call was a really great fit to work with. 

Bests,
Marcell

**Comment by t-bltg** [comment]
Hi !

Any contributing is welcome :+1:
Plus I think this feature was requested before in https://github.com/JuliaPlots/UnicodePlots.jl/issues/95.

You can open a PR in this repo, and we can polish the integration details in your PR.

**Comment by Cvikli** [comment]
Okay, I added the code here:

[vertical histrogram](https://github.com/JuliaPlots/UnicodePlots.jl/pull/221)

I see there is a Plot{<Canvas} style, which isn't fully understandable for me, so I didn't finish properly.

**Comment by Cvikli** [comment]
Hey sorry for being this slow on responding. I think I let this work to be done by someone else as my free time got filled up with another project. I made a post here: https://www.reddit.com/r/Julia/comments/t8yp23/julia_simple_unicode_plotting/ I hope someone will take the effort and integrate it to the main UnicodePlot repository by time. 

(Also I think there are some standardization on the input and the printing mechanism have to be changed if someone wants to merge into this library as I think there are some custom style over there I guess.)
