### ISSUE TITLE
using getting slower

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaPlots/UnicodePlots.jl#222]
Hi, I really like the latest 3D additions. UnicodePlots has been getting slower over time while the new 3D stuff seems not to blame.

Last version to be fast;
```
(@v1.7) pkg> add UnicodePlots@2.5.1

julia> @time using UnicodePlots
  0.394906 seconds (494.24 k allocations: 31.595 MiB, 3.83% compilation time)

vs.

(@v1.7) pkg> add UnicodePlots@2.6.0

julia> @time using UnicodePlots
  1.362755 seconds (2.61 M allocations: 192.173 MiB, 2.56% gc time, 1.02% compilation time)

and for latest:
julia> @time using UnicodePlots
  1.352334 seconds (2.68 M allocations: 197.087 MiB, 2.62% gc time, 0.92% compilation time)
```

At least this make later: https://github.com/JuliaPlots/UnicodePlots.jl/pull/217/files

Do you know what might explain?

**Comment by t-bltg** [comment]
Yes, this is explained by the added `StaticArrays` dependency since `2.6.0` (see https://github.com/JuliaPlots/UnicodePlots.jl/pull/206#issue-1108336640).

I'm not sure I can improve things here:
```
@time using StaticArrays
  0.909095 seconds (2.21 M allocations: 173.063 MiB, 3.48% gc time, 0.91% compilation time)
```

**Comment by johnnychen94** [comment]
This is indeed inconvenient and unpleasant from the users' perspective.

From juliahub.com, StaticArrays is used by 2072 packages, which is more than 1/3 of the packages in the General registry. At best we can hope we've already loaded `StaticArrays` directly or indirectly in real usage, thus it won't be too inconvenient:

```julia
julia> @time using StaticArrays
  0.576627 seconds (2.21 M allocations: 172.026 MiB, 0.30% compilation time)

julia> @time using UnicodePlots
  0.242409 seconds (482.87 k allocations: 31.661 MiB, 0.79% compilation time)
```

There is a long thread in discourse about StaticArrays ["[When should a package move to the standard library or system image? StaticArrays, what is it?](https://discourse.julialang.org/t/when-should-a-package-move-to-the-standard-library-or-system-image-staticarrays-what-is-it/73577)"](https://discourse.julialang.org/t/when-should-a-package-move-to-the-standard-library-or-system-image-staticarrays-what-is-it/73577). Until StaticArrays itself get improved or replaced, I don't think we have many choices here.

**Comment by mcabbott** [comment]
How is StaticArrays used? It's not immediately obvious from searching the code. But since the above messages, there is now a StaticArraysCore package which is much lighter.

**Comment by t-bltg** [comment]
It is used to project 3d coordinates onto a 2d canvas.
The basis for volumetric data is [here](https://github.com/JuliaPlots/UnicodePlots.jl/blob/master/src/volume.jl), and is is also used in 3d interfaces such as [surfaceplot](https://github.com/JuliaPlots/UnicodePlots.jl/blob/master/src/interface/surfaceplot.jl).

We use `StaticArrays` types (hence `StaticArraysCore` under the hood), but also `StaticArrays` functionalities, so we can not solely depend on `StaticArraysCore`.
