### ISSUE TITLE
parametrizable density transformation functions for `densityplot`/`histogram`

### ISSUE THREAD

**Issue by exaexa** [JuliaPlots/UnicodePlots.jl#226]
Hello!
First, thanks for UnicodePlots, this works magnificently for having the important quick peek at the data.

My issue/idea: It is often quite useful to be able to transform the densities displayed in the plot, in order to see specifics of the data. In case of UnicodePlots, this would allow users to focus specifically on say the high-density or low-density features of densityplots, possibly improving display (esp. given there are only like 5 or 6 "color levels" available). The most common use-case for such transformation is to avoid peaks in the data (say, if you have most pixels with values <10 and 1 pixel with value > 9000) from breaking the linear scale and causing all other pixels than the peak to be "empty".

I originally wanted to implement an interface like:
```julia
densityplot(..., dscale=x->log(1+x))
histogram(..., dscale=sqrt)
```
...but it appears that the parameters to Plot need to be passed manually to the Canvas constructors, and their interface currently has to be unified, so I preventively gave up before a possibly huge change, and went to ask here:
- Would it make sense do add some kind of "density scale" function parameter to all Canvases? Are there possibly other plot types to benefit from this than densityplot/histogram? (for contour plot/heatmap this is easy, you just change the function manually.... side thought: is there a way to plot contours out of "scatterplot"-style data?)
- Is there perhaps some workaround to make such a transform work with current version of DensityPlots?

Thanks!
-mk

**Comment by t-bltg** [comment]
> would it make sense do add some kind of "density scale" function parameter to all Canvases?

`xscale` and `yscale` are supported by all `canvas`es, did you try using this ? If that doesn't work, please provide a simple mwe with the expected output so that we fully understand what is missing.

> side thought: is there a way to plot contours out of "scatterplot"-style data?)

This doesn't seem to be supported by `Contour.jl`, quoting https://juliageometry.github.io/Contour.jl/stable/tutorial.html#Preface:-some-test-data...-1:
> z is a matrix arranged such that z[xi,yi] correspond to the location (x[xi], y[yi]).

If you wish this to be integrated, I'd suggest opening a dedicated issue in [`Contour.jl`](https://github.com/JuliaGeometry/Contour.jl), so that we could integrate it afterwards (boils down to `AbstractMatrix` -> `AbstractVecOrMat` change in `UnicodePlots`).

**Comment by exaexa** [comment]
Yes, it's basically the `zscale` as a function. I've seen there's already some `val_scale` but that is only linear, maybe the parameter could be reused?

Thanks for pointing out with the contour; I guess that at worst I can just throw a RBF there, no support in UnicodePlots needed then.

**Comment by exaexa** [comment]
The use-case displayed in R (using one of my other packages for brevity, so not-really-standard but it should show the idea)

```r
d <- (cbind(x=rnorm(100000),y=rnorm(100000))/3)^3
par(mfrow=c(1,3))
EmbedSOM::PlotEmbed(d, fdens=identity, main='Identity')
EmbedSOM::PlotEmbed(d, fdens=sqrt, main='sqrt')
EmbedSOM::PlotEmbed(d, fdens=function(x)log(1+x), main='log1p')
```
![image](https://user-images.githubusercontent.com/271543/153380266-2e58d8fe-8a27-4e51-ae86-3784e920bf65.png)

While the resolution is borderline okay here even with `identity` aka linear coloring, we've got much less colors in UnicodePlots

**Comment by t-bltg** [comment]
Thanks for the example (even if `R` is gibberish to me :laughing:, never used it !). I get the idea, we now have to find a suitable mathematical formulation.

**Comment by exaexa** [comment]
> R is gibberish

R is a domain specific language in the domain of R :D

> suitable mathematical formulation

In my attempt I did the following:
- removed the "accumulated maximum" variable from the Canvas and instead calculated the maximum only before plotting (a bit slower but what, the canvas is like 100x100 :D )
- transformed the maximum with the `zscale` function (There's a bit of a danger with division by zero at https://github.com/JuliaPlots/UnicodePlots.jl/blob/master/src/canvas/densitycanvas.jl#L101, I solved by using `... / max(eps(), zscale(maximum(c.grid)))`
- at https://github.com/JuliaPlots/UnicodePlots.jl/blob/master/src/canvas/densitycanvas.jl#L101 I wrapped the `zscale(c.grid[x,y])`
- then I found the fact about unified interfaces and went to ask here. :D

**Comment by t-bltg** [comment]
Do you this working in a fork branch somewhere ?
