### ISSUE TITLE
Support for Unitful types

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/UnicodePlots.jl#230]
Is it possible to create a lineplot with Unitful data? I tried plotting a time series of temperature in degrees Celsius but it throws and error message saying that < is not implemented for Number and Unitful.

**Comment by t-bltg** [comment]
In principle, I would say that it is reasonable to ask for support of this since `Unitful` has a [single external dependency](https://github.com/PainterQubits/Unitful.jl/blob/f9992c08c5917f0cb6402bce26cd0a71a61ceb97/Project.toml#L6) : `ConstructionBase` (apart from a bunch of `stdlib`s).

Can you please provide a simple `mwe`, showing what you expect to work ?

**Comment by juliohm** [comment]
Thank you for considering it. Here is a MWE:

```julia
julia> using Unitful
u
julia> using UnicodePlots

julia> y = [22., 23., 24.]*u"°C"
3-element Vector{Quantity{Float64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, Unitful.Affine{-5463//20}}}}:
 22.0 °C
 23.0 °C
 24.0 °C

julia> lineplot(y)
ERROR: DimensionError: 0.0 and 24.0 °C are not dimensionally compatible.
```

The solution can be as easy as stripping out the units internally, and adding some label to the axis to show degree Celsius:

```julia
julia> lineplot(ustrip.(y))
```

Or maybe you could refactor the internals to avoid direct comparisons between 0 and unitful types? I know `oneunit` exists, but I don't know if the equivalent `zerounit` is available.

**Comment by briochemc** [comment]
Was [UnitfulRecipes.jl](https://github.com/jw3126/UnitfulRecipes.jl) not working?

**Comment by t-bltg** [comment]
> Was [UnitfulRecipes.jl](https://github.com/jw3126/UnitfulRecipes.jl) not working?

It is if you are using the `UnicodePlots` backend through `Plots`. This is more low level when not using `Plots`.

**Comment by briochemc** [comment]
Oh I see! I was thinking maybe you found something wrong with UnitfulRecipes...
