### ISSUE TITLE
No separation between bars in histogramplot

### ISSUE THREAD

**Issue by AtheistApe** [JuliaPlots/UnicodePlots.jl#235]
Greetings,

When I make a histogram plot, there is no separation between the bars as shown here:

![image](https://user-images.githubusercontent.com/21245221/155754803-47bc5a98-deb8-4c3b-9328-73ef897ff0a5.png)

Is there a way to show a separation between the bars?

**Comment by t-bltg** [comment]
Hi, I was gonna say this is font dependent, but it doesn't seem like it :/.

**Comment by t-bltg** [comment]
Alternatively, you can pass `symbols = ['■']`, i.e. an smaller unicode symbol than the default used:

```julia
julia> using UnicodePlots
julia> histogram(randn(1000) .* .1, nbins=15, closed=:left, symbols=['■'])
                  ┌                                        ┐ 
   [-0.3 , -0.25) ┤ 2                                        
   [-0.25, -0.2 ) ┤■■■ 19                                    
   [-0.2 , -0.15) ┤■■■■■■■■ 51                               
   [-0.15, -0.1 ) ┤■■■■■■■■■■■■■■■■ 98                       
   [-0.1 , -0.05) ┤■■■■■■■■■■■■■■■■■■■■■■■ 141               
   [-0.05,  0.0 ) ┤■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 213   
   [ 0.0 ,  0.05) ┤■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 172          
   [ 0.05,  0.1 ) ┤■■■■■■■■■■■■■■■■■■■■■■■■■ 152             
   [ 0.1 ,  0.15) ┤■■■■■■■■■■■■■■■ 92                        
   [ 0.15,  0.2 ) ┤■■■■■■■ 43                                
   [ 0.2 ,  0.25) ┤■■ 14                                     
   [ 0.25,  0.3 ) ┤ 1                                        
   [ 0.3 ,  0.35) ┤ 2                                        
                  └                                        ┘ 
                                   Frequency                 
```

**Comment by AtheistApe** [comment]
Wow, such quick responses! Thanks.

For others that may be experiencing this issue, I found the problem and solution. 

The problem was with the profile settings of the terminal. When I adjusted the terminal settings, the issue disappeared. If you have this problem, try adjusting the terminal profile settings until you get something you're happy with.

**Comment by t-bltg** [comment]
Out of curiosity, what settings did you change (on which os ?)
