### ISSUE TITLE
Subplots with Term.jl - proposal

### ISSUE THREAD

**Issue by FedeClaudi** [JuliaPlots/UnicodePlots.jl#256]
As shown in https://github.com/FedeClaudi/Term.jl/issues/86, one can use `Term.jl` (which I'm developing) to create a layout made up of multiple `UnicodePlots` plots. 
I just wanted to bring this to your attention as a potentially very easy way to create figures layouts made up of multiple plots (I don't think that `UnicodePlots` has this features yet). 

Cheers, 
Fede

**Comment by t-bltg** [comment]
Well, we have basic layout support in `Plots.jl` (https://docs.juliaplots.org/stable/gallery/unicodeplots/generated/unicodeplots-ref17/).

`Term.jl` seems to handle more complex layouts, this could be an improvement. We could add `Term.jl` as a Plots dependency, but this looks like an overkill ...

See also how we handle this in `Plots.jl`: https://github.com/JuliaPlots/Plots.jl/blob/18b11a71e349cd826505fe260e293509bfb10847/src/backends/unicodeplots.jl#L316

**Comment by FedeClaudi** [comment]
awesome, I wasn't aware that you had a layout functionality already. Agreed, Term.jl might be too much then.
Thanks for the quick reply!

**Comment by FedeClaudi** [comment]
I've added a comment here https://github.com/JuliaPlots/UnicodePlots.jl/pull/258, but `string(plot; color=true)` already covers all that is needed I think?
