### ISSUE TITLE
Implement a save() function to provide generic solution for plots

### ISSUE THREAD

**Issue by Evizero** [JuliaPlots/UnicodePlots.jl#28]
as discussed in  #19

**Comment by Evizero** [comment]
@tbreloff I'll soon implement a save to txt file method. What would you suggest the method name/signature to be? `safefig(myplot, "filename.txt")` or would you suggest avoiding name collisions?

**Comment by tbreloff** [comment]
Cool!  Shouldn't matter to me... I only ever import, so all calls are
prefaced (UnicodePlots.savefig, etc).  Feel free to use the same naming as
in Plots.

**Comment by Evizero** [comment]
Alright. Looking at this now it seems I don't obey the subtle intended distinction between `show` and `print`, resulting in `print` writing color decorated text into any stream (even files), which make them unreadable. So that's the first thing to fix.

Other than that I am a bit reluctant now to make a special save method since it is probably best to just treat a `Plot` like one would a string (i.e. write them to a file the same way). An option to save the fully color decorated string may be useful though. especially if I ever want to create real tests for this package.

**Comment by hustf** [comment]
Bump.
Perhaps there's an obvious way, without a modification here? If so, I haven't been able to figure it out. When print or show to a file, an IOStream I get:
	
"[37m"
and so forth.

I've been copying from the REPL to a text file, which works but gets boring.

**Comment by digital-carver** [comment]
> Other than that I am a bit reluctant now to make a special save method since it is probably best to just treat a Plot like one would a string

In my opinion there's value in providing the common interface, such as the `savefig` method. A lot of the value of `Plots.jl` is in not having to relearn slightly different interfaces every time, instad having a common reliable interface. Having the "obvious thing" (saving with `savefig`) would lead a smoother interface, even if all it did underneath was a `print`.

**Comment by crstnbr** [comment]
Kindly bumping again. Would love to have simple `savefig` function in UnicodePlots!
