### ISSUE TITLE
Invalidations

### ISSUE THREAD

**Issue by alecloudenback** [JuliaPlots/UnicodePlots.jl#287]
Thank you for the package! I noticed that UnicodePlots has quite a bit of invalidations and didn't see another issue or discussion for it:

```julia-repl
julia> @time using UnicodePlots
  2.688526 seconds (8.91 M allocations: 604.171 MiB, 7.49% gc time, 18.85% compilation time: 94% of which was recompilation)
```

**Comment by t-bltg** [comment]
```julia
using SnoopCompile
println(invalidation_trees(@snoopr using UnicodePlots))
[...]
```

I don't see anything related to `UnicodePlots` in the output (`ChainRulesCore`, `DataStructures`, `ColorVectorSpace`, `GeometryBasics`, `StaticArrays`, `StatsBase`, `SortingAlgorithms`, `FreeTypeAbstraction`, `CEnum`, ...), so I'd suggest opening issues in dedicated packages for narrowing it down.
