### ISSUE TITLE
`DateTime` ticks not disappearing when setting `xticks=false` option

### ISSUE THREAD

**Issue by ghyatzo** [JuliaPlots/UnicodePlots.jl#292]
Hello,

when I tried plotting a timeseries using DateTime objects as the time, passing the `xticks=false` keyword does nothing and the bottom left and bottom right labels persists. 

The only way I found is using the `label!` function passing in an empty string but it is a bit hacky.

**Comment by t-bltg** [comment]
Could you post a [mwe](https://en.wikipedia.org/wiki/Minimal_reproducible_example) ?

**Comment by ghyatzo** [comment]
```
using DataFrames
using Dates
using UnicodePlots

df= DataFrame(Time=DateTime[], Test=Float64[])
for i = 1:100
	t = now()
	push!(df, [t, rand(1:100)])
	sleep(0.1)
end
lineplot(df.Time, df.Test; xticks=false, yticks=false)
```
gives me this
![Screenshot 2022-09-20 at 11 46 32](https://user-images.githubusercontent.com/8601724/191226038-8508aa62-3b39-4c96-a57c-e46bc6b90ec2.jpg)
