### ISSUE TITLE
Plots don't look quite as good in iterm

### ISSUE THREAD

**Issue by Keno** [JuliaPlots/UnicodePlots.jl#3]
<img width="528" alt="screen shot 2015-08-16 at 5 48 11 pm" src="https://cloud.githubusercontent.com/assets/1291671/9293991/053ffde4-443f-11e5-8ae2-e9785b0d77bc.png">

I think iTerm has line spacing, which doesn't get taken account by the painting algorithm, so the lines look off. Maybe the algorithm can be accounted to adjust for that (of course there will always be some spacing) or maybe @gnachman has a suggestion for how to make this look better (not that there is a real need since with iTerm you can always just embed a real plot as an inline image - but still).

**Comment by Evizero** [comment]
Mhm I did not expect that. Well, what I could do is tell the Canvas that a character is 6 pixel high instead of 4 and simply through away the upper two rows. That would however result in loss of data (for point plots for example)

**Comment by gnachman** [comment]
Could you make a shell log (shell>log>start, report, shell>log>end) and file an issue (iterm2.com/bugs) and include your plist file as requested in the bug template? Thanks!

**Comment by clason** [comment]
I think that's fixed by now?

<img width="385" alt="screenshot 2019-01-08 at 22 05 27" src="https://user-images.githubusercontent.com/2361214/50858717-8390c780-1391-11e9-928e-07cf4b60d1dc.png">

(iTerm2 v3.2.7beta3)
