### ISSUE TITLE
Add support for Axis scaling

### ISSUE THREAD

**Issue by Evizero** [JuliaPlots/UnicodePlots.jl#32]
Such as log-scale and such. Related to [39 of Plots.jl](https://github.com/tbreloff/Plots.jl/issues/39)

Will be a while before I get to this one, but I'll add it eventually.

**Comment by PetrKryslUCSD** [comment]
Has this happened? Are semi-log and log-log plots available?

**Comment by Evizero** [comment]
only for barplots / histograms thus far (see readme)
