### ISSUE TITLE
invert matrix when using heatmap

### ISSUE THREAD

**Issue by indymnv** [JuliaPlots/UnicodePlots.jl#320]
When applying a correlation matrix, it could be inverted as it tends to be shown in correlation matrices (with the diagonal of values one from the upper left corner). Currently, it is being shown in the opposite direction.

For example:
```julia
using DataFrames
using UnicodePlots

# Create a 9x9 matrix of random float values
data = rand(9, 9)

# Create a vector of column names
columns = [:col1, :col2, :col3, :col4, :col5, :col6, :col7, :col8, :col9]

# Create the dataframe
df = DataFrame(data, Symbol.(columns))

# Create a correlation matrix
cor_data = cor(Matrix(df))

heatmap(cor_data)
```

This will give the following output:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/50039428/209542296-e9d2560b-a4b4-428d-9dcb-e97db32403ef.png">

**Comment by t-bltg** [comment]
Hi,
I don't know why the convention was initially chosen to have the origin at the bottom left-hand corner, but we have a keyword `array` (documented under `heatmap`) that you can toggle in order to have the origin at the top left-hand corner (as in the repl):

```julia
julia> using UnicodePlots, Statistics, DataFrames
julia> data = rand(9, 9);
julia> columns = [:col1, :col2, :col3, :col4, :col5, :col6, :col7, :col8, :col9];
julia> df = DataFrame(data, Symbol.(columns));
julia> cor_data = cor(Matrix(df));
julia> heatmap(cor_data; array=true)
     ┌─────────┐  1  
   1 │▄▄▄▄▄▄▄▄▄│ ┌──┐
     │▄▄▄▄▄▄▄▄▄│ │▄▄│
     │▄▄▄▄▄▄▄▄▄│ │▄▄│
     │▄▄▄▄▄▄▄▄▄│ │▄▄│
   9 │▄▄▄▄▄▄▄▄▄│ └──┘
     └─────────┘ -0.8
      1       9      
```

**Comment by indymnv** [comment]
Oh, you are right, sorry I didn't get that in the documentation. Thank you for your time.

**Comment by t-bltg** [comment]
My pleasure !
Closing as it appears to be resolved.
