### ISSUE TITLE
Heatmap colorbar with non-finite values

### ISSUE THREAD

**Issue by milankl** [JuliaPlots/UnicodePlots.jl#321]
Heatmap without colorbar works fine for `Matrix{<:AbstractFloat}`, however, the colorbar throws an error once there are NaNs or Infs
```julia
julia> heatmap(rand(5,5),colorbar=true)
     ┌─────┐  1  
   5 │▄▄▄▄▄│ ┌──┐
     │▄▄▄▄▄│ │▄▄│
   1 │▄▄▄▄▄│ └──┘
     └─────┘ 0.02
      1   5      

julia> heatmap(rand(5,5)*NaN,colorbar=true)
Error showing value of type Plot{HeatmapCanvas{typeof(identity), typeof(identity)}, Val{false}, Bool}:
ERROR: InexactError: trunc(Int64, NaN)
Stacktrace:
  [1] trunc
    @ ./float.jl:781 [inlined]
  [2] floor
    @ ./float.jl:357 [inlined]
  [3] ceil_neg_log10(x::Float64)
    @ UnicodePlots ~/.julia/packages/UnicodePlots/vEerR/src/common.jl:347
  [4] float_round_log10(x::Float64, m::Float64)
    @ UnicodePlots ~/.julia/packages/UnicodePlots/vEerR/src/common.jl:367
  [5] float_round_log10
    @ ~/.julia/packages/UnicodePlots/vEerR/src/common.jl:363 [inlined]
  [6] (::UnicodePlots.var"#89#90"{Plot{HeatmapCanvas{typeof(identity), typeof(identity)}, Val{false}, Bool}})(x::Float64)
    @ UnicodePlots ~/.julia/packages/UnicodePlots/vEerR/src/show.jl:199
  [7] map
    @ ./tuple.jl:222 [inlined]
  [8] _show(end_io::IOContext{Base.TTY}, print_nocol::typeof(print), print_color::typeof(UnicodePlots.print_color), p::Plot{HeatmapCanvas{typeof(identity), typeof(identity)}, Val{false}, Bool})
    @ UnicodePlots ~/.julia/packages/UnicodePlots/vEerR/src/show.jl:198
  [9] show
    @ ~/.julia/packages/UnicodePlots/vEerR/src/show.jl:145 [inlined]
```
The problem arises from
https://github.com/JuliaPlots/UnicodePlots.jl/blob/bfaa6f8d61ed830745ffe21c1d207bc8054814e1/src/common.jl#L345-L348
as it doesn't work with x being non-finite
```julia
julia> UnicodePlots.ceil_neg_log10(1e300)
-300

julia> UnicodePlots.ceil_neg_log10(Inf)
ERROR: InexactError: trunc(Int64, -Inf)
```

**Comment by milankl** [comment]
I suggest to change that function to
```julia
function ceil_neg_log10(x)
    val = -log10(x)
    isfinite(val) || return typemin(Int)
    roundable(val) ? ceil(Int, val) : floor(Int, val)
end
```
such that 
```julia
julia> ceil_neg_log10(Inf)
-9223372036854775808

julia> ceil_neg_log10(1e300)
-300
```
the output is of the same type (`Int`) and the smallest representable to match the -log10(x) idea as best as possible. In the end it seems to be used here
https://github.com/JuliaPlots/UnicodePlots.jl/blob/bfaa6f8d61ed830745ffe21c1d207bc8054814e1/src/common.jl#L364-L368

where this works fine now
```julia
julia> round(Inf,digits=typemin(Int)+1)
Inf

julia> round(-Inf,digits=typemin(Int)+1)
-Inf

julia> round(NaN,digits=typemin(Int)+1)
NaN
```
If there are no objections, I'll create a pull request replacing the `ceil_neg_log10` function

**Comment by t-bltg** [comment]
Thanks for reporting.

First, I think the colorbar limit should not take `NaN`s into account. That is an easy fix replacing https://github.com/JuliaPlots/UnicodePlots.jl/blob/bfaa6f8d61ed830745ffe21c1d207bc8054814e1/src/interface/heatmap.jl#L115 with `NaNMath.extrema(A)`.

Then, I think we should ignore those NaN values when printing `Crayons`.

**Comment by milankl** [comment]
Yes, but it doesn't help if the entire field is NaN/Infs
```julia
julia> A = rand(2,2)
julia> A[1] = NaN
julia> NaNMath.extrema(A)
(0.18783010303710246, 0.9637507750862072)

julia> NaNMath.extrema(A*NaN)
(NaN, NaN)
```
I'm coming from a perspective where I run a simulation, hopefully everthing works fine and heatmap gives me a quick look that things look reasonable. However, when the simulation blows up I just see white stripes on the heatmap (which is good because then I know I did something wrong). But in that case I can't use the colorbar at the moment.
