### ISSUE TITLE
Plot border and axis markers are the same color as background

### ISSUE THREAD

**Issue by marekdedic** [JuliaPlots/UnicodePlots.jl#336]
Hi,
I thought my plot was missing the plot border, axes and their markers:

![Screenshot from 2023-02-23 11-21-54](https://user-images.githubusercontent.com/3134692/220880722-8e7854c8-cbca-411d-8e8e-729be39b485e.png)

However, when I select over the whole plot, it reveals they are there, just not shown:

![Screenshot from 2023-02-23 11-22-02](https://user-images.githubusercontent.com/3134692/220880826-e54236b0-1bc7-423d-b397-88de0c12222b.png)

I am using alacritty as my terminal emulator with the `tomorrow night` color theme.

**Comment by t-bltg** [comment]
You can change the border color like this, if the current overlaps with your terminal background color:
```julia
julia> using UnicodePlots
julia> UnicodePlots.BORDER_COLOR[] = :red
julia> lineplot(1:2)
[...]
```

**Comment by t-bltg** [comment]
1. Automatically ... to what ? We cannot detect the type of terminal / colorscheme you are working with.
2. Apart from doing the following, there is no other way:
```julia
julia> using Plots; unicodeplot()
julia> Plots.UnicodePlots.BORDER_COLOR[] = :white
```

**Comment by marekdedic** [comment]
1. Well I thought there was a way to detect the fg/bg color of the terminal - if there isn't, then yeah, there is no universal good choice...

**Comment by t-bltg** [comment]
I'd like to precise: there is no method to determine the colours to my current knowledge, which might be limited and of course I'm open to contributions regarding that matter. Furthermore, I use Linux, so I'm incompetent in anything related to windows.
