### ISSUE TITLE
histogram not defined

### ISSUE THREAD

**Issue by zhuxuangao** [JuliaPlots/UnicodePlots.jl#340]
I'm trying to reproduce the histogram plot example

> using UnicodePlots
> histogram(randn(1_000) .* .1, nbins=15, closed=:left)

And I got error that UndefVarError: histogram not defined

I'm using UnicodePlots v3.4.1

**Comment by zhuxuangao** [comment]
<img width="375" alt="Screen Shot 2023-03-31 at 3 08 43 PM" src="https://user-images.githubusercontent.com/101985347/229208399-8d119af3-66e7-436b-8316-96b240fa953a.png">

**Comment by t-bltg** [comment]
I've just tried on julia 1.8.5, and it also works.

Can you try using `UnicodePlots.histogram(...)`, see if that works ?

**Comment by zhuxuangao** [comment]
It works! Thanks! However when I tried scatterplot example:scatterplot(randn(50), randn(50), title="My Scatterplot")
I used both 
`using UnicodePlots
UnicodePlots.scatterplot(randn(50), randn(50), title="My Scatterplot")`
and
`using UnicodePlots
scatterplot(randn(50), randn(50), title="My Scatterplot")`

They both produce
<img width="362" alt="Screen Shot 2023-03-31 at 3 15 29 PM" src="https://user-images.githubusercontent.com/101985347/229209571-c12c088a-89e2-4274-9d5d-eac4f5f34d16.png">
The same issue also appears in 
`lineplot([1, 2, 7], [9, -6, 8], title="My Lineplot")`
Is there anyway to get the same output as yours?

**Comment by t-bltg** [comment]
This is probably because your font does not support braille characters.
There is a note in https://github.com/JuliaPlots/UnicodePlots.jl#known-issues.

Alternatively, you can use another canvas, based on ascii characters:

```julia
using UnicodePlots
lineplot([1, 2, 7], [9, -6, 8], title="My Lineplot", canvas=DotCanvas, border=:ascii)
```

**Comment by zhuxuangao** [comment]
It works! Thanks!
