### ISSUE TITLE
Despite Project.toml update, StatsBase 0.34 is not compatible with UnicodePlots 3.5.2

### ISSUE THREAD

**Issue by ablaom** [JuliaPlots/UnicodePlots.jl#355]
This is causing me some downstream headaches:

```julia
(@work) pkg> activate --temp
(jl_6CDbRH) pkg> add UnicodePlots
(jl_6CDbRH) pkg> st -m --outdated
Status `/private/var/folders/4n/gvbmlhdc8xj973001s6vdyw00000gq/T/jl_6CDbRH/Manifest.toml`
⌅ [2913bbd2] StatsBase v0.33.21 (<v0.34.0): UnicodePlots

(jl_6CDbRH) pkg> st
Status `/private/var/folders/4n/gvbmlhdc8xj973001s6vdyw00000gq/T/jl_6CDbRH/Project.toml`
  [b8865327] UnicodePlots v3.5.2
```

This is despite #354 . Furthermore, if I clone UnicodePlots and instantiate the Project.toml there, I get the latest StatsBase 0.34 (even after adding weak dependencies). 

So, I checked out the entry at General, and see that no StatsBase 0.34 appears in the [Compat.toml](https://github.com/JuliaRegistries/General/blob/master/U/UnicodePlots/Compat.toml).??  I've no idea why.

**Comment by t-bltg** [comment]
See https://github.com/JuliaRegistries/General/pull/83166, a new version (3.5.3) will be available in a few minutes.

**Comment by ablaom** [comment]
Thanks. I thought I checked the UnicodePlots version number at General but must have remembered the number wrong. Sorry for the confusion and thanks for tagging a new release!
