### ISSUE TITLE
Can I use UnicodePlots.jl by launching Julia script via command line (not in REPL mode)

### ISSUE THREAD

**Issue by algorithmx** [JuliaPlots/UnicodePlots.jl#360]
Dear developers,

I want to integrated UnicodePlots.jl into my package and launch a piece of code via command line

```
$julia main.jl
```
where main.jl contains some drawing command with the UnicodePlots.jl package. But the plot does not show up. Can anyone tell me what to do? Thanks.

**Comment by t-bltg** [comment]
Use `display` as in : `display(lineplot(1:2))`.

**Comment by algorithmx** [comment]
Yes it is possible with `println(canvas)`

**Comment by algorithmx** [comment]
> Use `display` as in : `display(lineplot(1:2))`.

thank you !
