### ISSUE TITLE
support xflip and yflip for heatmaps

### ISSUE THREAD

**Issue by fredcallaway** [JuliaPlots/UnicodePlots.jl#400]
In particular, yflip would be really nice because this is the orientation in which matrices are printed.

**Comment by t-bltg** [comment]
Are you looking for the `array` keyword ?

```julia
help?> heatmap
[...]
    •  array : use array display convention (origin at the North-West
       corner of the plot, hence flipping y versus regular plots).
```

**Comment by fredcallaway** [comment]
I guess I was—although I still adding yflip as a synonym would make sense for consistency with the rest of the package (and Plots.jl)

**Comment by t-bltg** [comment]
Yeah, I don't remember why `array` was added, especially since `xflip` and `yflip` seem to be supported natively by `heatmap` and the underlying canvas.

**Comment by t-bltg** [comment]
Can I close this issue since `yflip` is working as expected here ?

**Comment by fredcallaway** [comment]
I'm so sorry—I have no idea how I managed to convince myself that yflip wasn't supported.
