### ISSUE TITLE
X axis misalignment in Yakuake

### ISSUE THREAD

**Issue by rdeits** [JuliaPlots/UnicodePlots.jl#91]
I just tried out the new UnicodePlots 1.0.0, and it looks perfect in the standard default Ubuntu terminal, but the x axis seems to be consistently out of alignment when I render the same plots in [yakuake](https://www.kde.org/applications/system/yakuake/) which is the terminal emulator I use most often. For example, here's a plot of y=x:

![screenshot from 2019-01-07 13-23-44](https://user-images.githubusercontent.com/591886/50785705-7edbee80-127f-11e9-9655-cba743af0e1e.png)

The offset seems to be independent of my choice of font. Is there anything I can do to fix and/or help debug this?

**Comment by Evizero** [comment]
I am afraid I have never seen this effect before. I do know that the Braille characters tend to cause issues here and there depending on the font etc. 

The only workaround I can suggest is to use `canvas = DotCanvas` which is half the resolution of the braille one but pure ascii

**Comment by warrendale** [comment]
![image](https://user-images.githubusercontent.com/46302867/50796497-c5d9dc00-129f-11e9-8761-6c427cdd8af2.png)

I also noticed something similar when plotting inside JupyerLab

**Comment by Evizero** [comment]
yes this is known. for some reason the font in jupyter doesn't think monospace should apply to Braille characters

**Comment by t-bltg** [comment]
Closing in favor of https://github.com/JuliaPlots/UnicodePlots.jl/issues/9.
