### ISSUE TITLE
Enhancement Suggestion: box-plot for categorical data

### ISSUE THREAD

**Issue by natemcintosh** [JuliaPlots/UnicodePlots.jl#92]
I absolutely love the box-plot capability! How hard would it be to add capability to plot categorical data, as opposed to strings? 

Alternatively, I might just be missing a very easy and obvious conversion from categorical to string to make this work.

**Comment by Evizero** [comment]
do you have a minimal working example that shows what you'd like to be able to do?

**Comment by natemcintosh** [comment]
Sure! I do lots of work with DataFrames with categorical data so I've set up this example with one.

`using DataFrames, CategoricalArrays, UnicodePlots`
`gender = ["female", "male", "male", "female", "male", "female"]`
` test_score = [78,65,70,87,65,25]`
`df_example = DataFrame(gender = gender, test_scores = test_score)`
`categorical!(df_example, :gender)`
`boxplot(df_example.gender, df_example.test_scores)`

The [original file](https://www.kaggle.com/spscientist/students-performance-in-exams) is a Kaggle Dataset on education

**Comment by t-bltg** [comment]
Closing since the example does not work: `categorical!` undefined.

Please provide another example using `DataFrames` if needed, and we'll consider reopening.
