### ISSUE TITLE
limits should accept tuples

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/UnicodePlots.jl#96]
```
UnicodePlots.scatterplot(is, js, xlim = (1, n), ylim = (1, m))
```
should work without having the need to have `xlim = [1,n]`.

At the moment I get: `ERROR: TypeError: in Type, in typeassert, expected AbstractArray{T,1} where T, got Tuple{Int64,Int64}`.

**Comment by Evizero** [comment]
yes I have been thinking that as well lately

**Comment by Datseris** [comment]
Thanks a lot for this! Would you be kind to tag a new release so I could included in our repo as well?
